export const provinces = [
    {pid:'1', name:'Province 1'},
    {pid:'2', name:'Madhesh Pradesh'},
    {pid:'3', name:'Bagmati Pradesh'},
    {pid:'4', name:'Gandaki Pradesh'},
    {pid:'5', name:'Lumbini Pradesh'},
    {pid:'6', name:'Karnali Pradesh'},
    {pid:'7', name:'Sudur Pashchim Pradesh'},
]

export const districts=[
    {pid:'1', did:'1', name:'Bhojpur'},
    {pid:'1', did:'2', name:'Dhankuta'},
    {pid:'1', did:'3', name:'Ilam'},
    {pid:'1', did:'4', name:'Jhapa'},
    {pid:'1', did:'5', name:'Khotang'},
    {pid:'1', did:'6', name:'Morang'},
    {pid:'1', did:'7', name:'Okhaldhunga'},
    {pid:'1', did:'8', name:'Panchthar'},
    {pid:'1', did:'9', name:'Sankhuwasabha'},
    {pid:'1', did:'10', name:'Solukhumbu'},
    {pid:'1', did:'11', name:'Sunsari'},
    {pid:'1', did:'12', name:'Taplejung'},
    {pid:'1', did:'13', name:'Tehrathum'},
    {pid:'1', did:'14', name:'Udayapur'},
    {pid:'2', did:'15', name:'Bara'},
    {pid:'2', did:'16', name:'Dhanusha'},
    {pid:'2', did:'17', name:'Mahottari'},
    {pid:'2', did:'18', name:'Parsa'},
    {pid:'2', did:'19', name:'Rautahat'},
    {pid:'2', did:'20', name:'Saptari'},
    {pid:'2', did:'21', name:'Sarlahi'},
    {pid:'2', did:'22', name:'Siraha'},
    {pid:'3', did:'23', name:'Bhaktapur '},
    {pid:'3', did:'24', name:'Chitwan'},
    {pid:'3', did:'25', name:'Dhading'},
    {pid:'3', did:'26', name:'Dolakha'},
    {pid:'3', did:'27', name:'Kathmandu'},
    {pid:'3', did:'28', name:'Kavrepalanchok'},
    {pid:'3', did:'29', name:'Lalitpur'},
    {pid:'3', did:'30', name:'Makawanpur'},
    {pid:'3', did:'31', name:'Nuwakot '},
    {pid:'3', did:'32', name:'Ramechhap'},
    {pid:'3', did:'33', name:'Rasuwa'},
    {pid:'3', did:'34', name:'Sindhuli'},
    {pid:'3', did:'35', name:'Sindhupalchok'},
    {pid:'4', did:'36', name:'Baglung'},
    {pid:'4', did:'37', name:'Gorkha'},
    {pid:'4', did:'38', name:'Kaski'},
    {pid:'4', did:'39', name:'Lamjung'},
    {pid:'4', did:'40', name:'Manang'},
    {pid:'4', did:'41', name:'Mustang'},
    {pid:'4', did:'42', name:'Myagdi'},
    {pid:'4', did:'43', name:'Nawalparasi east'},
    {pid:'4', did:'44', name:'Parbat'},
    {pid:'4', did:'45', name:'Syangja'},
    {pid:'4', did:'46', name:'Tanahu'},
    {pid:'5', did:'47', name:'Arghakhanchi'},
    {pid:'5', did:'48', name:'Banke'},
    {pid:'5', did:'49', name:'Bardiya'},
    {pid:'5', did:'50', name:'Dang'},
    {pid:'5', did:'51', name:'Gulmi'},
    {pid:'5', did:'52', name:'Kapilvastu'},
    {pid:'5', did:'53', name:'Nawalparasi west'},
    {pid:'5', did:'54', name:'Palpa'},
    {pid:'5', did:'55', name:'Pyuthan'},
    {pid:'5', did:'56', name:'Rolpa'},
    {pid:'5', did:'57', name:'Purbi Rukum'},
    {pid:'5', did:'58', name:'Rupandehi'},
    {pid:'6', did:'59', name:'Dailekh'},
    {pid:'6', did:'60', name:'Dolpa'},
    {pid:'6', did:'61', name:'Humla'},
    {pid:'6', did:'62', name:'Jajarkot'},
    {pid:'6', did:'63', name:'Jumla'},
    {pid:'6', did:'64', name:'Kalikot'},
    {pid:'6', did:'65', name:'Mugu'},
    {pid:'6', did:'66', name:'Rukum Paschim'},
    {pid:'6', did:'67', name:'Salyan'},
    {pid:'6', did:'68', name:'Surkhet'},
    {pid:'7', did:'69', name:'Achham'},
    {pid:'7', did:'70', name:'Baitadi'},
    {pid:'7', did:'71', name:'Bajhang'},
    {pid:'7', did:'72', name:'Bajura'},
    {pid:'7', did:'73', name:'Dadeldhura'},
    {pid:'7', did:'74', name:'Darchula'},
    {pid:'7', did:'75', name:'Doti'},
    {pid:'7', did:'76', name:'Kailali'},
    {pid:'7', did:'77', name:'Kanchanpur'},
    
]

export const municipalities = [
    {did:'27', name:'Kathmandu Metropolitian'},
    {did:'27', name:'Budhanilkantha'},
    {did:'27', name:'Tarakeshwar'},
    {did:'27', name:'Gokarneshwar'},
    {did:'27', name:'Chandragiri'},
    {did:'27', name:'Tokha'},
    {did:'27', name:'Kageshwari-Manohara'},
    {did:'27', name:'Nagarjun'},
    {did:'27', name:'Kirtipur'},
    {did:'23', name:'Bhaktapur'},
    {did:'23', name:'Changunarayan'},
    {did:'23', name:'Madhyapur Thimi'},
    {did:'23', name:'Suryabinayak'},
    {did:'29', name:'Lalitpur Metropolitan'},
    {did:'29', name:'Mahalaxmi'},
    {did:'29', name:'Godawari'},
    {did:'29', name:'Konjyoson'},
    {did:'29', name:'Bagmati'},
    {did:'29', name:'Mahankal'},
    {did:'28', name:'Dhulikhel'},
    {did:'28', name:'Banepa'},
    {did:'28', name:'Panauti'},
    {did:'28', name:'Panchkhal'},
    {did:'28', name:'Namobuddha'},
    {did:'28', name:'Mandandeupur'},
    {did:'28', name:'Khani Khola'},
    {did:'28', name:'Chauri Deurali'},
    {did:'28', name:'Temal Rural'},
    {did:'28', name:'Bethanchok'},
    {did:'28', name:'Bhumlu Rural'},
    {did:'28', name:'Mahabharat'},
    {did:'28', name:'Roshi Rural'},
    {did:'38', name:'Pokhara Metropolitan'},
    {did:'38', name:'Annapurna'},
    {did:'38', name:'Machhapuchchhre'},
    {did:'38', name:'Madi'},
    {did:'38', name:'Rupa'},
]